[QA-142] Adding time to post build to flush metrics
alphagov/di-devplatform-performance pull request #55
Opened 2023-04-19 13:59 UTC by Tom-Dann

## QA-142

Adding a 5 minute wait to the post-build action to allow time to flush remaining OpenTelemetry metrics before agent teardown

2023-04-19 14:06 UTC, abhinaysrivastavaperf approved these changes

2023-04-24 13:32 UTC, beca-galliano approved these changes

2023-04-24 13:34 UTC, andyloughran requested changes
Shouldn't include time-based waits - let's put something in that will check if the buffer is flushed.

2023-04-24 13:34 UTC, andyloughran commented on deploy/template.yaml
> +                - echo Wait 5 minutes to flush remaining metrics
Can we find a better way to do this please?

2023-05-04 16:57 UTC, jamesmelville-gds approved these changes

2023-05-05 11:12 UTC, merged